version: '3.3'
services:
    zfile:
        container_name: zfile
        restart: always
        ports:
            - '${TRIM_SERVICE_PORT}:8080'
        volumes:
            - '/${TRIM_APPDEST_VOL}/@appshare/${TRIM_APPNAME}/db:/root/.zfile-v4/db'
            - '/${TRIM_APPDEST_VOL}/@appshare/${TRIM_APPNAME}/logs:/root/.zfile-v4/logs'
            - '/${TRIM_APPDEST_VOL}/@appshare/${TRIM_APPNAME}/file:/data/file'
        image: zhaojun1998/zfile:latest